[package]
name = "phonotypst"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Guilherme D. Garcia <guilherme.garcia@lli.ulaval.ca>"]
license = "MIT"
description = "A phonology toolkit: IPA transcription with tipa-style input (includes Charis SIL font) and prosodic structure visualization"
repository = "https://github.com/guilhermegarcia/phonotypst"
keywords = ["linguistics", "ipa", "phonology", "prosody", "phonetics"]

[dependencies]
cetz = "0.4.2"
